### ISSUE TITLE
AttributeError: type object 'COCOObject' has no attribute 'from_detection'[BUG]

### ISSUE THREAD

**Issue by IremYoldas** [voxel51/fiftyone-examples#31]
Hey, I'm trying to run "fiftyone_pytorch_training.py". And I'm getting this error. When I search the method that is "from_detection" i didn't find anything about this method. I would be glad if you help. Thank you for your answer in advance.

**Comment by ehofesmann** [comment]
@IremYoldas Thanks for pointing that out! The `COCOObject.from_detection()` method was renamed to [`COCOObject.from_label()`](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/utils/coco.py#L1115). I will update the example.

**Comment by IremYoldas** [comment]
> @IremYoldas Thanks for pointing that out! The `COCOObject.from_detection()` method was renamed to [`COCOObject.from_label()`](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/utils/coco.py#L1115). I will update the example.

Thanks a lot!! You're a life saver!

**Comment by IremYoldas** [comment]
> 

Thanks a lot!! You're a life saver!
